function InternalBarForces = ANSYS_Force(filename, dataLines)
%IMPORTFILE Import data from a text file
%  INTERNALBARFORCES = IMPORTFILE(FILENAME) reads data from text file
%  FILENAME for the default selection.  Returns the data as a table.
%
%  INTERNALBARFORCES = IMPORTFILE(FILE, DATALINES) reads data for the
%  specified row interval(s) of text file FILENAME. Specify DATALINES as
%  a positive scalar integer or a N-by-2 array of positive scalar
%  integers for dis-contiguous row intervals.
%
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 09-Nov-2019 12:19:37

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [505, Inf];
end

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 8);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = " ";

% Specify column names and types
opts.VariableNames = ["PRINT", "F", "ELEMENT", "SOLUTION", "Var5", "Var6", "Var7", "Var8"];
opts.SelectedVariableNames = ["PRINT", "F", "ELEMENT", "SOLUTION"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "string", "string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";
opts.ConsecutiveDelimitersRule = "join";
opts.LeadingDelimitersRule = "ignore";

% Specify variable properties
opts = setvaropts(opts, ["Var5", "Var6", "Var7", "Var8"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Var5", "Var6", "Var7", "Var8"], "EmptyFieldRule", "auto");

% Import the data
InternalBarForces = readtable(filename, opts);

end